/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author scast
 */
public class Vista_Clientes extends javax.swing.JFrame {

    public Vista_Clientes() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        buttonReset.setActionCommand("Res");
    }

    public void setActionListener(ActionListener al) {
        buttonComenzar.addActionListener(al);
        buttonReset.addActionListener(al);
    }

    public void setButtonComenzar(JButton buttonComenzar) {
        this.buttonComenzar = buttonComenzar;
    }

    public void setButtonReset(JButton buttonReset) {
        this.buttonReset = buttonReset;
    }

    public void setCheckboxMostrar(JCheckBox checkboxMostrar) {
        this.checkboxMostrar = checkboxMostrar;
    }

    public JButton getButtonComenzar() {
        return buttonComenzar;
    }

    public JButton getButtonReset() {
        return buttonReset;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelNumClientes = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        textNumClientes = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textDetalles = new javax.swing.JTextArea();
        labelDesconectados = new javax.swing.JLabel();
        buttonComenzar = new javax.swing.JButton();
        labelActivos = new javax.swing.JLabel();
        labelTotales = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        checkboxMostrar = new javax.swing.JCheckBox();
        labelDetalles = new javax.swing.JLabel();
        textIp = new javax.swing.JTextField();
        labelNumClientes5 = new javax.swing.JLabel();
        buttonReset = new javax.swing.JButton();
        textPuerto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelNumClientes6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Generar clientes - Proyecto ARC");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 57, 63));

        labelNumClientes.setFont(new java.awt.Font("Gadugi", 0, 16)); // NOI18N
        labelNumClientes.setForeground(new java.awt.Color(255, 255, 255));
        labelNumClientes.setText("Número de clientes");

        labelTitulo.setFont(new java.awt.Font("Gadugi", 0, 26)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setText("Simulador de clientes");

        textNumClientes.setBackground(new java.awt.Color(40, 46, 51));
        textNumClientes.setFont(new java.awt.Font("Gadugi", 0, 15)); // NOI18N
        textNumClientes.setForeground(new java.awt.Color(255, 255, 255));
        textNumClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNumClientesActionPerformed(evt);
            }
        });
        textNumClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textNumClientesKeyPressed(evt);
            }
        });

        textDetalles.setEditable(false);
        textDetalles.setBackground(new java.awt.Color(40, 46, 51));
        textDetalles.setColumns(20);
        textDetalles.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        textDetalles.setForeground(new java.awt.Color(255, 255, 255));
        textDetalles.setRows(5);
        textDetalles.setFocusable(false);
        jScrollPane1.setViewportView(textDetalles);

        labelDesconectados.setFont(new java.awt.Font("Gadugi", 0, 15)); // NOI18N
        labelDesconectados.setForeground(new java.awt.Color(255, 255, 255));
        labelDesconectados.setText("Clientes desconectados: ");

        buttonComenzar.setBackground(new java.awt.Color(40, 46, 51));
        buttonComenzar.setFont(new java.awt.Font("Gadugi", 0, 16)); // NOI18N
        buttonComenzar.setForeground(new java.awt.Color(255, 255, 255));
        buttonComenzar.setText("Comenzar Simulación");
        buttonComenzar.setFocusable(false);
        buttonComenzar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonComenzarMouseClicked(evt);
            }
        });
        buttonComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonComenzarActionPerformed(evt);
            }
        });

        labelActivos.setFont(new java.awt.Font("Gadugi", 0, 15)); // NOI18N
        labelActivos.setForeground(new java.awt.Color(255, 255, 255));
        labelActivos.setText("Clientes activos: ");

        labelTotales.setFont(new java.awt.Font("Gadugi", 0, 15)); // NOI18N
        labelTotales.setForeground(new java.awt.Color(255, 255, 255));
        labelTotales.setText("Clientes totales: ");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));

        checkboxMostrar.setBackground(new java.awt.Color(51, 57, 63));
        checkboxMostrar.setFont(new java.awt.Font("Gadugi", 0, 13)); // NOI18N
        checkboxMostrar.setForeground(new java.awt.Color(255, 255, 255));
        checkboxMostrar.setText("Mostrar detalles de la ejecución");
        checkboxMostrar.setActionCommand("Detalles de la ejecución");
        checkboxMostrar.setFocusable(false);
        checkboxMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxMostrarActionPerformed(evt);
            }
        });

        labelDetalles.setFont(new java.awt.Font("Gadugi", 0, 15)); // NOI18N
        labelDetalles.setForeground(new java.awt.Color(255, 255, 255));
        labelDetalles.setText("Detalles: Ocultos");

        textIp.setBackground(new java.awt.Color(40, 46, 51));
        textIp.setFont(new java.awt.Font("Gadugi", 0, 15)); // NOI18N
        textIp.setForeground(new java.awt.Color(102, 255, 255));
        textIp.setText("127.0.0.1");
        textIp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textIpFocusLost(evt);
            }
        });
        textIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIpActionPerformed(evt);
            }
        });
        textIp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textIpKeyPressed(evt);
            }
        });

        labelNumClientes5.setFont(new java.awt.Font("Gadugi", 0, 15)); // NOI18N
        labelNumClientes5.setForeground(new java.awt.Color(255, 255, 255));
        labelNumClientes5.setText("Servidor");

        buttonReset.setBackground(new java.awt.Color(40, 46, 51));
        buttonReset.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        buttonReset.setForeground(new java.awt.Color(255, 255, 255));
        buttonReset.setText("Local");
        buttonReset.setFocusable(false);

        textPuerto.setBackground(new java.awt.Color(40, 46, 51));
        textPuerto.setFont(new java.awt.Font("Gadugi", 0, 15)); // NOI18N
        textPuerto.setForeground(new java.awt.Color(153, 153, 255));
        textPuerto.setText("5000");
        textPuerto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textPuertoFocusLost(evt);
            }
        });
        textPuerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPuertoActionPerformed(evt);
            }
        });
        textPuerto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textPuertoKeyPressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(102, 255, 255));
        jLabel1.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 255));
        jLabel1.setText("ip");

        jLabel2.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setText("puerto");

        labelNumClientes6.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        labelNumClientes6.setForeground(new java.awt.Color(255, 255, 255));
        labelNumClientes6.setText("Detalles de la ejecución");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(labelNumClientes6)
                        .addGap(366, 366, 366))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkboxMostrar)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(buttonComenzar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelActivos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelTotales, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelDesconectados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelDetalles, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(textIp, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(textPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(labelNumClientes5)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(buttonReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelNumClientes)
                                .addGap(17, 17, 17)
                                .addComponent(textNumClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTitulo)
                    .addComponent(labelNumClientes6))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNumClientes)
                            .addComponent(textNumClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNumClientes5)
                            .addComponent(buttonReset)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(labelActivos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelDesconectados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTotales)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelDetalles)
                        .addGap(18, 18, 18)
                        .addComponent(checkboxMostrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonComenzar, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNumClientesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNumClientesKeyPressed
    }//GEN-LAST:event_textNumClientesKeyPressed

    private void checkboxMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxMostrarActionPerformed
    }//GEN-LAST:event_checkboxMostrarActionPerformed

    private void textIpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textIpKeyPressed
    }//GEN-LAST:event_textIpKeyPressed

    private void textIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIpActionPerformed
    }//GEN-LAST:event_textIpActionPerformed

    private void textPuertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPuertoActionPerformed
    }//GEN-LAST:event_textPuertoActionPerformed

    private void textPuertoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPuertoKeyPressed
    }//GEN-LAST:event_textPuertoKeyPressed

    private void textNumClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNumClientesActionPerformed
    }//GEN-LAST:event_textNumClientesActionPerformed

    private void buttonComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonComenzarActionPerformed
    }//GEN-LAST:event_buttonComenzarActionPerformed

    private void textPuertoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textPuertoFocusLost
    }//GEN-LAST:event_textPuertoFocusLost

    private void textIpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textIpFocusLost
    }//GEN-LAST:event_textIpFocusLost

    private void buttonComenzarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonComenzarMouseClicked
        if (textNumClientes.getText().equals("")||
                textPuerto.getText().equals("") || textIp.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Introduce valores en los campos de texto activos");
        } else {
            //Para que no llame al controlador en el caso de que los campos estan vacios
            buttonComenzar.setActionCommand("Ini");
            buttonComenzar.doClick();
            buttonComenzar.setActionCommand("");
        }
    }//GEN-LAST:event_buttonComenzarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonComenzar;
    private javax.swing.JButton buttonReset;
    public javax.swing.JCheckBox checkboxMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel labelActivos;
    public javax.swing.JLabel labelDesconectados;
    public javax.swing.JLabel labelDetalles;
    private javax.swing.JLabel labelNumClientes;
    private javax.swing.JLabel labelNumClientes5;
    private javax.swing.JLabel labelNumClientes6;
    private javax.swing.JLabel labelTitulo;
    public javax.swing.JLabel labelTotales;
    protected javax.swing.JTextArea textDetalles;
    public javax.swing.JTextField textIp;
    public javax.swing.JTextField textNumClientes;
    public javax.swing.JTextField textPuerto;
    // End of variables declaration//GEN-END:variables
}
